// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_types

type CreateUserInput struct {
	Username *string `json:"username"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
